export const CUSTOM_COLOR = {
  White: '#FFFFFF',
  Black: '#000000',
  RedBasic: '#d0343f',
  Abbey: '#4A4D51',
  Alabaster: '#F9F9F9',
  Alto: '#DFDFDF',
  AltoAlpha: 'rgba(219, 219, 219, 0.71)',
  AltoDark: '#D9D9D9',
  AthensGray: '#F6F7F9',
  BlackAlpha50: 'rgba(0, 0, 0, 0.5)',
  Bizarre: '#F1DEDF',
  BondiBlue: '#009CB1',
  Bunker: '#101719',
  Cardinal: '#BE1E2D',
  CatalinaBlue: '#073375',
  CatskillWhite: '#F2F5F9',
  Chambray: '#31558C',
  CodGray: '#0A0A0A',
  CodGrayLight: '#1D1B1B',
  CoralRed: '#FF434F',
  CornflowerBlue: '#63B2F3',
  CuriousBlue: '#2D9CDB',
  DustyGray: '#979797',
  DustyGrayDark: '#999999',
  DodgerBlue: '#2FA0FB',
  Orange: '#F08C31',
  OrangeOpacity: '#F08C3140',
  Envy: '#8DAA9B',
  Gallery: '#EDEDED',
  GalleryDark: '#F0F0F0',
  Goblin: '#367C4D',
  Ghost: '#C0C3D4',
  GreenPea: '#17483E',
  GreenBold: '#0B2520',
  GumLeaf: '#A7CDB8',
  Iceberg: '#D8F2F0',
  Iron: '#DEDEE0',
  Lochmara: '#0086CB',
  Mercury: '#E5E5E5',
  ShuttleGray: '#636466',
  MineShaft: '#2A2A2A',
  Nevada: '#676A6F',
  PastelGreen: '#71E397',
  PersianGreen: '#00B495',
  Persimmon: '#FF5555',
  PurpleHeart: '#8E3BD6',
  Red: '#FF0000',
  RegentGray: '#8694A3',
  GrayLight: '#F8F9FA',
  RoyalBlue: '#217FEB',
  RoyalBluePurple: '#5D5FEF',
  Silver: '#C4C4C4',
  SilverChalice: '#AFAFAF',
  SpunPearl: '#A9A9B2',
  Shark: '#1A1A1C',
  Tuna: '#303036',
  Tenn: '#CC6600',
  ToryBlue: '#164DA4',
  Tundora: '#444444',
  Whisper: '#F7F8FB',
  WildSand: '#F4F4F4',
  WhiteGray: '#F4F6F8',
  Woodsmoke: '#0A0A0B',
  Sliver: '#F5F5F5',
  BlueStone: '#005E52',
  MidGray: '#60606C',
  Transparent: 'transparent',
  Concrete: '#F3F3F3',
  Seashell: '#F1F1F1',
  SurfieGreen: '#138B76',
  Java: '#1CD6B5',
  SandyBrownAlpha20: 'rgba(245,172,88,0.2)',
  TangoAlpha20: 'rgba(239,128,34,0.2)',
  SandyBrown: '#F5AC58',
  Tango: '#EF8022',
  Bombay: '#B1B3B6',
  OsloGray: '#939598',
  AltoAlpha71: 'rgba(219, 219, 219, 0.71)',
  Burnham: '#002520',
  BurnhamAlpha20: 'rgba(0, 36, 31, 0.05)',
  SharkAlpha10: 'rgba(39, 39, 40, 0.1)',
  GreyDivider: '#E6E7E8',
  Flamingo: '#EF413D',
  SeaBuckthorn: '#F59830',
  LightOrange: '#F99D33',
  Saffron: '#F9C233',
  LightPink: '#FBE2CB',
  grayBoder: '#CCD1D9',
  textBlack: '#313131',
  GreenSuccess: '#449460',
  RedError: '#EE2624',
  TextGray: '#A3A3A3',
  LightGreen: '#25BF22',
  MidnightBlue: '#E3F2FD',
  XDarkBlue: '#323a4d',
  MainTab: '#FFFFFF',
  BasicGray: '#eae7e2',
  Pink: '#ffe5e4',
  modalSystem: 'rgba(167,167,167,0.7)',
  Pomegranateapprox: '#F12533'
};

export const TEXT_COLOR = {
  RedBasic: CUSTOM_COLOR.RedBasic,
  Primary: CUSTOM_COLOR.BlueStone,
  PrimaryDisable: CUSTOM_COLOR.RegentGray,
  Purple: CUSTOM_COLOR.PurpleHeart,
  Orange: CUSTOM_COLOR.Orange,
  GreenLight: CUSTOM_COLOR.PersianGreen,
  Gray: CUSTOM_COLOR.RegentGray,
  ShuttleGray: CUSTOM_COLOR.ShuttleGray,
  Red: CUSTOM_COLOR.Red,
  Black: CUSTOM_COLOR.Black,
  ToryBlue: CUSTOM_COLOR.ToryBlue,
  White: CUSTOM_COLOR.White,
  Secondary: CUSTOM_COLOR.CodGray,
  SecondaryDisable: CUSTOM_COLOR.DustyGrayDark,
  PlaceHolder: CUSTOM_COLOR.RegentGray,
  Inactive: CUSTOM_COLOR.MidGray,
  Main: CUSTOM_COLOR.Goblin,
  GreenPea: CUSTOM_COLOR.GreenPea,
  GreenBold: CUSTOM_COLOR.GreenBold,
  OsloGray: CUSTOM_COLOR.OsloGray,
  Chambray: CUSTOM_COLOR.Chambray,
  Bunker: CUSTOM_COLOR.Bunker,
  RoyalBluePurple: CUSTOM_COLOR.RoyalBluePurple,
  Woodsmoke: CUSTOM_COLOR.Woodsmoke,
  CuriousBlue: CUSTOM_COLOR.CuriousBlue,
  CornflowerBlue: CUSTOM_COLOR.CornflowerBlue,
  Silver: CUSTOM_COLOR.Silver,
  Nevada: CUSTOM_COLOR.Nevada,
  Goblin: CUSTOM_COLOR.Goblin,
  PrimaryDarker: CUSTOM_COLOR.GreenPea,
  BlueStone: CUSTOM_COLOR.BlueStone,
  Bombay: CUSTOM_COLOR.Bombay,
  Flamingo: CUSTOM_COLOR.Flamingo,
  textBlack: CUSTOM_COLOR.textBlack,
  TextGray: CUSTOM_COLOR.TextGray,
  MidnightBlue: CUSTOM_COLOR.MidnightBlue,
  XDarkBlue: CUSTOM_COLOR.XDarkBlue,
  MainTab: CUSTOM_COLOR.MainTab,
  BasicGray: CUSTOM_COLOR.BasicGray,
  Pink: CUSTOM_COLOR.Pink,
  modalSystem: CUSTOM_COLOR.modalSystem,
  Pomegranateapprox: CUSTOM_COLOR.Pomegranateapprox
};

export const BACKGROUND_COLOR = {
  RedBasic: CUSTOM_COLOR.RedBasic,
  Primary: CUSTOM_COLOR.White,
  Secondary: CUSTOM_COLOR.Alto,
  GreenLight: CUSTOM_COLOR.PersianGreen,
  White: CUSTOM_COLOR.White,
  Gray: CUSTOM_COLOR.Tundora,
  Black: CUSTOM_COLOR.Black,
  RoyalBlue: CUSTOM_COLOR.RoyalBlue,
  Mercury: CUSTOM_COLOR.Mercury,
  Bombay: CUSTOM_COLOR.Bombay,
  CatalinaBlue: CUSTOM_COLOR.CatalinaBlue,
  ToryBlue: CUSTOM_COLOR.ToryBlue,
  AltoAlpha71: CUSTOM_COLOR.AltoAlpha71,
  Silver: CUSTOM_COLOR.Silver,
  GreenPea: CUSTOM_COLOR.GreenPea,
  Goblin: CUSTOM_COLOR.Goblin,
  Whisper: CUSTOM_COLOR.Whisper,
  OsloGray: CUSTOM_COLOR.OsloGray,
  RegentGray: CUSTOM_COLOR.RegentGray,
  GrayLight: CUSTOM_COLOR.GrayLight,
  Flamingo: CUSTOM_COLOR.Flamingo,
  SeaBuckthorn: CUSTOM_COLOR.SeaBuckthorn,
  BlueStoneOpa8: CUSTOM_COLOR.BlueStone + '14',
  LightOrange: CUSTOM_COLOR.LightOrange,
  OrangeOpa8: CUSTOM_COLOR.Orange + '14',
  BlueStone: CUSTOM_COLOR.BlueStone,
  LightPink: CUSTOM_COLOR.LightPink,
  Orange: CUSTOM_COLOR.Orange,
  GreenSuccess: CUSTOM_COLOR.GreenSuccess,
  RedError: CUSTOM_COLOR.RedError,
  LightGreen: CUSTOM_COLOR.LightGreen,
  XDarkBlue: CUSTOM_COLOR.XDarkBlue,
  MainTab: CUSTOM_COLOR.MainTab,
  BasicGray: CUSTOM_COLOR.BasicGray,
  Pink: CUSTOM_COLOR.Pink,
  modalSystem: CUSTOM_COLOR.modalSystem,
  Pomegranateapprox: CUSTOM_COLOR.Pomegranateapprox
};

export const HEADER_COLOR = CUSTOM_COLOR.White;

export const BUTTON_COLOR = {
  Primary: CUSTOM_COLOR.Orange,
  PrimaryOpacity: CUSTOM_COLOR.OrangeOpacity,
  DisablePrimary: CUSTOM_COLOR.Silver,
  Secondary: CUSTOM_COLOR.SilverChalice,
  modalSystem: CUSTOM_COLOR.modalSystem
};

export const COLOR_ACTIVE = '#F5831E';
export const COLOR_INACTIVE = '#60606C';
